GITLAB_TOKEN=#{GITLAB_TOKEN}
GITLAB_PROJECT_NAME=#{GITLAB_PROJECT_NAME}
GITLAB_SHARED_RUNNER_ID=#{GITLAB_SHARED_RUNNER_ID}
OCTOAPI=#{OCTOAPI}
OCTO_TENANT_ID=#{OCTO_TENANT_ID}
Development=#{Development}